version: "3"

services:
  portainer:
    image: portainer/portainer-ce:2.9.3
    container_name: portainer_agent
    restart: always
    ports:
      - "9001:9001"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
